FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install -g @angular/cli

COPY . .

RUN ng build --configuration production --build-optimizer

EXPOSE 4200

CMD ["ng","serve","--host", "0.0.0.0", "--disable-host-check"]


