version: '3.8'

services:
  mongo:
    image: ravillaramu1/sit:sit-mongo-latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=situser
      - MONGO_INITDB_ROOT_PASSWORD=sitadmin
    networks:
      - my-network

  mongo-express:
    image: ravillaramu1/sit:sit-mongo-express-latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=situser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=sitadmin
    networks:
      - my-network

  frontend:
    image: ravillaramu1/sit:sit-frontend-latest
    container_name: frontend
    ports:
      - "4200:4200"
    restart: unless-stopped
    depends_on:
      - mongo
      - backend
    networks:
      - my-network

  backend:
    image: ravillaramu1/sit:sit-backend-latest
    container_name: backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - my-network
  nginx:
    image: ravillaramu1/sit:sit-nginx-latest
    container_name: nginx
    ports:
      - "8082:8082"
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    networks:
      - my-network
    volumes:
      - ./opt/nginx/logs:/var/log/nginx       
      - ./opt/nginx/certificates:/etc/letsencrypt

networks:
  my-network:
    driver: bridge

